spring:
  profiles:
    active: home
  application:
    name: pfds-user
server:
  port: 19061
logging:
  config: classpath:logback-pfds-user.xml
#跳闸的最小请求数量
hystrix: 
  command: 
    default: 
      circuitBreaker: 
        requestVolumeThreshold: 10